### ISSUE TITLE
404: This page could not be found

### ISSUE THREAD

**Issue by jellyfishing2346** [bc-compsci-club/bccs-club#45]
There appears to be a 404 message when being brought to the home page. 
This was brought to my attention by someone in the Discord server for the CS Club.
Link: https://bccs.club/a

<img width="1280" alt="Screen Shot 2024-08-29 at 9 25 20 AM" src="https://github.com/user-attachments/assets/55e5d74f-3b40-40d9-9ec2-eb8f38524b26">

**Comment by Qingquan-Li** [comment]
@jellyfishing2346 do you want to report a bug? if so, please label it as “bug” (follow the documentation: Contributing Guidelines).
however, according to your description, it’s not a bug because we didn’t build a page for "bccs.club/a", so it is supposed to show nothing (404).
Similarly, if you open bccs.club/b or bccs.club/c, it will also be 404.

**Comment by jellyfishing2346** [comment]
@Qingquan-Li I do since this a bug reported by someone in the discord server.
